options:
  node-exporter-version:
    type: string
    default: "1.2.0"
    description: >
      The node-exporter version to install.
  listen-address:
    type: string
    default: "0.0.0.0:9100"
    description: The address to listen to.
  labels:
    type: string
    default: ""
    description: >
      Comma-separated list of custom labels for the metrics exported.

      Example: 'foo=bar, key=value'
